name: workflow for Codecov

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHON: '3.7'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
        id: go
    
    - name: Generate coverage report
      run: |
        go test `go list ./... | grep -v examples` -coverprofile=coverage.txt -covermode=atomic

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        files: coverage.txt
        flags: unittests
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
