name: markdownlink

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
    paths:
      - '*.md'
jobs:
  lint-markdown-docs:
    name: Lint markdown file
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint markdown file
      uses: docker://dragonflyoss/linter:v0.2.7
      with:
        args: find . -name .md | xargs mdl
