name: Markdown Link Check

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
    paths:
      - '*.md'
jobs:
  markdown-docs-link-check:
    name: check links in markdown files
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: check links in markdown files
      uses: docker://dragonflyoss/linter:v0.2.7
      with:
        args: bash -c "for mdFile in $(find ./ -name '*.md' | grep -v vendor); do markdown-link-check -q $mdFile; if [ $? -ne 0 ]; then code=1; fi;done;bash -c 'exit $code'"

