name: Markdown Link Check

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
    paths:
      - '*.md'
jobs:
  markdown-docs-link-check:
    name: check links in markdown files
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: check links in markdown files
      uses: docker://dragonflyoss/linter:v0.2.7
      with:
        args: bash -c "find ./ -name '*.md' | grep -v vendor | xargs markdown-link-check"

